name: 'question validation'
description: 'action to validate question schemas'
author: 'Ada'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  INPUT_FILES:
    description: 'files to be validates, formated as a JSON array (e.g. ["file1.json", "file2.json"])'
    required: true

runs:
  using: node20
  main: dist/index.js
