name: 'question validation'
description: 'action to validate question schemas'
author: 'Ada'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
